### ISSUE TITLE
Reduce padding to more closely match design

### ISSUE THREAD

**Issue by liammalby** [liammalby/qr-code-image#2]
In updating the accessibility between v0.1 and v0.1, I changed the layout of the QR code such that my version no longer closely matches the design brief. It appears to be an issue with the padding of the whitespace.

The issues likely arose out of these changes made in [this commit](https://github.com/liammalby/qr-code-image/commit/dc25be2e1914b8f146953fb261f0d9c16f84add9).

**Comment by shyamtawli** [comment]
Hey @liammalby can you describe more?

**Comment by liammalby** [comment]
> Hey @liammalby can you describe more?

Hi @shyamtawli I have added further description in the initial comment.
